<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.ypbin.starter</groupId>
        <artifactId>ypbin-starter-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../ypbin-starter-dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>ypbin-starter-cloud-gateway</artifactId>

    <name>${project.artifactId}</name>
    <description>网关：基于 Spring Cloud Gateway（WebFlux），统一跨域、请求 ID、全局异常</description>

    <properties>
        <revision>1.0.0-SNAPSHOT</revision>
    </properties>

    <dependencies>
        <dependency>
            <groupId>cn.ypbin.starter</groupId>
            <artifactId>ypbin-starter-core</artifactId>
        </dependency>

        <!-- Spring Cloud Gateway 基于 WebFlux（响应式），与 servlet 模块技术栈不同 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
