<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.ypbin</groupId>
        <artifactId>ypbin-starter-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../ypbin-starter-dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>ypbin-starter-social</artifactId>

    <name>${project.artifactId}</name>
    <description>第三方登录：基于 JustAuth 的 OAuth 登录（微信/QQ/GitHub 等），可插拔 state 缓存</description>

    <properties>
        <revision>1.0.0</revision>
    </properties>

    <dependencies>
        <dependency>
            <groupId>cn.ypbin</groupId>
            <artifactId>ypbin-starter-core</artifactId>
        </dependency>

        <dependency>
            <groupId>me.zhyd.oauth</groupId>
            <artifactId>JustAuth</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
